<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $exercises = [
            [
                'title' => 'Build a Simple Calculator',
                'title_bn' => 'একটি সাধারণ ক্যালকুলেটর তৈরি করুন',
                'description' => 'Create a basic calculator that can perform addition, subtraction, multiplication, and division.',
                'description_bn' => 'একটি মৌলিক ক্যালকুলেটর তৈরি করুন যা যোগ, বিয়োগ, গুণ এবং ভাগ করতে পারে।',
                'instructions' => 'Implement a calculator class with methods for basic arithmetic operations. Handle division by zero errors appropriately. Test your implementation with various test cases.',
                'instructions_bn' => 'মৌলিক গাণিতিক অপারেশনের জন্য মেথড সহ একটি ক্যালকুলেটর ক্লাস বাস্তবায়ন করুন। শূন্য দ্বারা ভাগ ত্রুটিগুলি যথাযথভাবে পরিচালনা করুন। বিভিন্ন পরীক্ষার ক্ষেত্রে আপনার বাস্তবায়ন পরীক্ষা করুন।',
                'difficulty' => 'easy',
                'difficulty_bn' => 'সহজ',
                'duration' => 30,
                'duration_bn' => '৩০ মিনিট',
                'category' => 'Programming Basics',
                'category_bn' => 'প্রোগ্রামিং বেসিক',
                'tags' => ['JavaScript', 'Beginner', 'Functions'],
                'tags_bn' => ['জাভাস্ক্রিপ্ট', 'শিক্ষানবিস', 'ফাংশন'],
                'starter_code' => 'function add(a, b) {\n  // Your code here\n}\n\nfunction subtract(a, b) {\n  // Your code here\n}\n\nfunction multiply(a, b) {\n  // Your code here\n}\n\nfunction divide(a, b) {\n  // Your code here\n}',
                'solution_code' => 'function add(a, b) {\n  return a + b;\n}\n\nfunction subtract(a, b) {\n  return a - b;\n}\n\nfunction multiply(a, b) {\n  return a * b;\n}\n\nfunction divide(a, b) {\n  if (b === 0) {\n    throw new Error("Cannot divide by zero");\n  }\n  return a / b;\n}',
                'programming_language' => 'JavaScript',
                'image_url' => 'https://picsum.photos/800/400?random=101',
                'slug' => 'build-a-simple-calculator',
                'status' => 'published',
                'views' => 1456,
                'completions' => 823,
                'published_at' => now()->subDays(10),
            ],
            [
                'title' => 'Implement a Binary Search Algorithm',
                'title_bn' => 'একটি বাইনারি সার্চ অ্যালগরিদম বাস্তবায়ন করুন',
                'description' => 'Write an efficient binary search algorithm to find an element in a sorted array.',
                'description_bn' => 'একটি সাজানো অ্যারেতে একটি উপাদান খুঁজে পেতে একটি দক্ষ বাইনারি সার্চ অ্যালগরিদম লিখুন।',
                'instructions' => 'Implement the binary search algorithm using recursion or iteration. The function should return the index of the target element if found, or -1 if not found. Analyze the time complexity of your solution.',
                'instructions_bn' => 'পুনরাবৃত্তি বা পুনরাবৃত্তি ব্যবহার করে বাইনারি সার্চ অ্যালগরিদম বাস্তবায়ন করুন। যদি পাওয়া যায় তবে ফাংশনটি লক্ষ্য উপাদানটির সূচক ফেরত দেবে, বা যদি না পাওয়া যায় তবে -1 ফেরত দেবে। আপনার সমাধানের সময় জটিলতা বিশ্লেষণ করুন।',
                'difficulty' => 'medium',
                'difficulty_bn' => 'মাঝারি',
                'duration' => 45,
                'duration_bn' => '৪৫ মিনিট',
                'category' => 'Algorithms',
                'category_bn' => 'অ্যালগরিদম',
                'tags' => ['Python', 'Algorithms', 'Search'],
                'tags_bn' => ['পাইথন', 'অ্যালগরিদম', 'সার্চ'],
                'starter_code' => 'def binary_search(arr, target):\n    # Your code here\n    pass',
                'solution_code' => 'def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    \n    while left <= right:\n        mid = (left + right) // 2\n        \n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    \n    return -1',
                'programming_language' => 'Python',
                'image_url' => 'https://picsum.photos/800/400?random=102',
                'slug' => 'implement-binary-search-algorithm',
                'status' => 'published',
                'views' => 2341,
                'completions' => 1234,
                'published_at' => now()->subDays(8),
            ],
            [
                'title' => 'Create a Todo List Component',
                'title_bn' => 'একটি টুডু লিস্ট কম্পোনেন্ট তৈরি করুন',
                'description' => 'Build a React component for a simple todo list with add, delete, and toggle functionality.',
                'description_bn' => 'যোগ, মুছে ফেলা এবং টগল কার্যকারিতা সহ একটি সাধারণ টুডু লিস্টের জন্য একটি React কম্পোনেন্ট তৈরি করুন।',
                'instructions' => 'Create a React functional component using hooks. Implement state management for the todo list. Add functionality to add new todos, mark them as complete, and delete them. Style the component using CSS.',
                'instructions_bn' => 'হুক ব্যবহার করে একটি React ফাংশনাল কম্পোনেন্ট তৈরি করুন। টুডু লিস্টের জন্য স্টেট ম্যানেজমেন্ট বাস্তবায়ন করুন। নতুন টুডু যোগ করার, সেগুলিকে সম্পূর্ণ হিসাবে চিহ্নিত করার এবং মুছে ফেলার কার্যকারিতা যোগ করুন। CSS ব্যবহার করে কম্পোনেন্টটি স্টাইল করুন।',
                'difficulty' => 'easy',
                'difficulty_bn' => 'সহজ',
                'duration' => 60,
                'duration_bn' => '৬০ মিনিট',
                'category' => 'Frontend Development',
                'category_bn' => 'ফ্রন্টএন্ড ডেভেলপমেন্ট',
                'tags' => ['React', 'JavaScript', 'Components'],
                'tags_bn' => ['রিঅ্যাক্ট', 'জাভাস্ক্রিপ্ট', 'কম্পোনেন্ট'],
                'starter_code' => 'import React, { useState } from \'react\';\n\nfunction TodoList() {\n  // Your code here\n  \n  return (\n    <div>\n      {/* Your JSX here */}\n    </div>\n  );\n}\n\nexport default TodoList;',
                'solution_code' => 'import React, { useState } from \'react\';\n\nfunction TodoList() {\n  const [todos, setTodos] = useState([]);\n  const [input, setInput] = useState(\'\');\n\n  const addTodo = () => {\n    if (input.trim()) {\n      setTodos([...todos, { id: Date.now(), text: input, completed: false }]);\n      setInput(\'\');\n    }\n  };\n\n  const toggleTodo = (id) => {\n    setTodos(todos.map(todo => \n      todo.id === id ? { ...todo, completed: !todo.completed } : todo\n    ));\n  };\n\n  const deleteTodo = (id) => {\n    setTodos(todos.filter(todo => todo.id !== id));\n  };\n\n  return (\n    <div className="todo-list">\n      <input value={input} onChange={(e) => setInput(e.target.value)} />\n      <button onClick={addTodo}>Add</button>\n      <ul>\n        {todos.map(todo => (\n          <li key={todo.id}>\n            <span style={{ textDecoration: todo.completed ? \'line-through\' : \'none\' }}>\n              {todo.text}\n            </span>\n            <button onClick={() => toggleTodo(todo.id)}>Toggle</button>\n            <button onClick={() => deleteTodo(todo.id)}>Delete</button>\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nexport default TodoList;',
                'programming_language' => 'JavaScript',
                'image_url' => 'https://picsum.photos/800/400?random=103',
                'slug' => 'create-todo-list-component',
                'status' => 'published',
                'views' => 1876,
                'completions' => 945,
                'published_at' => now()->subDays(5),
            ],
            [
                'title' => 'Reverse a Linked List',
                'title_bn' => 'একটি লিঙ্কড লিস্ট উল্টান',
                'description' => 'Implement a function to reverse a singly linked list in-place.',
                'description_bn' => 'একটি একক লিঙ্কড লিস্ট ইন-প্লেস উল্টানোর জন্য একটি ফাংশন বাস্তবায়ন করুন।',
                'instructions' => 'Write a function that takes the head of a linked list and reverses it. Do not use extra space for another list. Return the new head of the reversed list. Consider both iterative and recursive approaches.',
                'instructions_bn' => 'একটি ফাংশন লিখুন যা একটি লিঙ্কড লিস্টের হেড নেয় এবং এটি উল্টে দেয়। অন্য তালিকার জন্য অতিরিক্ত স্থান ব্যবহার করবেন না। উল্টানো তালিকার নতুন হেড ফেরত দিন। পুনরাবৃত্তি এবং পুনরাবৃত্তি উভয় পদ্ধতি বিবেচনা করুন।',
                'difficulty' => 'medium',
                'difficulty_bn' => 'মাঝারি',
                'duration' => 40,
                'duration_bn' => '৪০ মিনিট',
                'category' => 'Data Structures',
                'category_bn' => 'ডেটা স্ট্রাকচার',
                'tags' => ['Java', 'Linked List', 'Data Structures'],
                'tags_bn' => ['জাভা', 'লিঙ্কড লিস্ট', 'ডেটা স্ট্রাকচার'],
                'starter_code' => 'class ListNode {\n    int val;\n    ListNode next;\n    ListNode(int x) { val = x; }\n}\n\npublic class Solution {\n    public ListNode reverseList(ListNode head) {\n        // Your code here\n    }\n}',
                'solution_code' => 'class ListNode {\n    int val;\n    ListNode next;\n    ListNode(int x) { val = x; }\n}\n\npublic class Solution {\n    public ListNode reverseList(ListNode head) {\n        ListNode prev = null;\n        ListNode current = head;\n        \n        while (current != null) {\n            ListNode nextTemp = current.next;\n            current.next = prev;\n            prev = current;\n            current = nextTemp;\n        }\n        \n        return prev;\n    }\n}',
                'programming_language' => 'Java',
                'image_url' => 'https://picsum.photos/800/400?random=104',
                'slug' => 'reverse-linked-list',
                'status' => 'published',
                'views' => 3421,
                'completions' => 1789,
                'published_at' => now()->subDays(12),
            ],
            [
                'title' => 'Build a REST API Endpoint',
                'title_bn' => 'একটি REST API এন্ডপয়েন্ট তৈরি করুন',
                'description' => 'Create a RESTful API endpoint for user registration with validation and error handling.',
                'description_bn' => 'বৈধতা এবং ত্রুটি পরিচালনা সহ ব্যবহারকারী নিবন্ধনের জন্য একটি RESTful API এন্ডপয়েন্ট তৈরি করুন।',
                'instructions' => 'Implement a POST endpoint for user registration. Validate input data (email format, password strength). Hash passwords before storing. Return appropriate HTTP status codes and error messages. Use Express.js or Laravel.',
                'instructions_bn' => 'ব্যবহারকারী নিবন্ধনের জন্য একটি POST এন্ডপয়েন্ট বাস্তবায়ন করুন। ইনপুট ডেটা যাচাই করুন (ইমেল ফরম্যাট, পাসওয়ার্ড শক্তি)। সংরক্ষণের আগে পাসওয়ার্ড হ্যাশ করুন। উপযুক্ত HTTP স্ট্যাটাস কোড এবং ত্রুটি বার্তা ফেরত দিন। Express.js বা Laravel ব্যবহার করুন।',
                'difficulty' => 'hard',
                'difficulty_bn' => 'কঠিন',
                'duration' => 90,
                'duration_bn' => '৯০ মিনিট',
                'category' => 'Backend Development',
                'category_bn' => 'ব্যাকএন্ড ডেভেলপমেন্ট',
                'tags' => ['Node.js', 'Express', 'REST API'],
                'tags_bn' => ['নোড.জেএস', 'এক্সপ্রেস', 'REST API'],
                'starter_code' => 'const express = require(\'express\');\nconst app = express();\n\napp.use(express.json());\n\napp.post(\'/api/register\', async (req, res) => {\n  // Your code here\n});\n\napp.listen(3000, () => console.log(\'Server running\'));',
                'solution_code' => 'const express = require(\'express\');\nconst bcrypt = require(\'bcrypt\');\nconst app = express();\n\napp.use(express.json());\n\nconst validateEmail = (email) => {\n  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email);\n};\n\nconst validatePassword = (password) => {\n  return password.length >= 8;\n};\n\napp.post(\'/api/register\', async (req, res) => {\n  try {\n    const { email, password, name } = req.body;\n    \n    if (!email || !password || !name) {\n      return res.status(400).json({ error: \'All fields are required\' });\n    }\n    \n    if (!validateEmail(email)) {\n      return res.status(400).json({ error: \'Invalid email format\' });\n    }\n    \n    if (!validatePassword(password)) {\n      return res.status(400).json({ error: \'Password must be at least 8 characters\' });\n    }\n    \n    const hashedPassword = await bcrypt.hash(password, 10);\n    \n    // Save user to database (pseudo code)\n    // const user = await User.create({ email, password: hashedPassword, name });\n    \n    res.status(201).json({ message: \'User registered successfully\' });\n  } catch (error) {\n    res.status(500).json({ error: \'Internal server error\' });\n  }\n});\n\napp.listen(3000, () => console.log(\'Server running\'));',
                'programming_language' => 'JavaScript',
                'image_url' => 'https://picsum.photos/800/400?random=105',
                'slug' => 'build-rest-api-endpoint',
                'status' => 'published',
                'views' => 2987,
                'completions' => 1456,
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Two Sum Problem',
                'title_bn' => 'টু সাম সমস্যা',
                'description' => 'Find two numbers in an array that add up to a target sum.',
                'description_bn' => 'একটি অ্যারেতে দুটি সংখ্যা খুঁজুন যা একটি লক্ষ্য যোগফলে যোগ করে।',
                'instructions' => 'Given an array of integers and a target sum, return the indices of two numbers that add up to the target. You may assume that each input has exactly one solution. Optimize for time complexity.',
                'instructions_bn' => 'পূর্ণসংখ্যার একটি অ্যারে এবং একটি লক্ষ্য যোগফল দেওয়া হলে, লক্ষ্যে যোগ করা দুটি সংখ্যার সূচক ফেরত দিন। আপনি ধরে নিতে পারেন যে প্রতিটি ইনপুটের ঠিক একটি সমাধান রয়েছে। সময় জটিলতার জন্য অপ্টিমাইজ করুন।',
                'difficulty' => 'easy',
                'difficulty_bn' => 'সহজ',
                'duration' => 25,
                'duration_bn' => '২৫ মিনিট',
                'category' => 'Algorithms',
                'category_bn' => 'অ্যালগরিদম',
                'tags' => ['Python', 'Arrays', 'Hash Map'],
                'tags_bn' => ['পাইথন', 'অ্যারে', 'হ্যাশ ম্যাপ'],
                'starter_code' => 'def two_sum(nums, target):\n    # Your code here\n    pass',
                'solution_code' => 'def two_sum(nums, target):\n    num_map = {}\n    \n    for i, num in enumerate(nums):\n        complement = target - num\n        \n        if complement in num_map:\n            return [num_map[complement], i]\n        \n        num_map[num] = i\n    \n    return []',
                'programming_language' => 'Python',
                'image_url' => 'https://picsum.photos/800/400?random=106',
                'slug' => 'two-sum-problem',
                'status' => 'published',
                'views' => 4521,
                'completions' => 3245,
                'published_at' => now()->subDays(15),
            ],
        ];

        foreach ($exercises as $exercise) {
            Exercise::create($exercise);
        }
    }
}
